spring.application.name=SpringSecurityTask1Employee

server.port=${PORT:8080}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update